# Generated by Django 4.2.3 on 2023-07-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('normal', 'нормально'), ('not important', 'не важливо'), ('very important', 'дуже важливо')], default='not important', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'В очікуванні'), ('in_progress', 'В процесі'), ('completed', 'Завершено')], default='pending', max_length=30),
        ),
    ]
