# Generated by Django 4.2.3 on 2023-07-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='static',
            name='overdue_tasks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
